name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  package:
    name: Maven Package
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Build with Maven
        run: mvn package --file pom.xml
